In [18]:
import pandas as pd
import numpy as np

Товары категории A:
  • Высокая оборачиваемость, большая доля выручки
  • Требуют строгого контроля, точного прогнозирования, минимальных страховых запасов

Товары категории B: 
  • Умеренный спрос, средний вклад в прибыль
  • Контроль по регламенту, периодический пересмотр запасов

Товары категории C: 
  • Низкая оборачиваемость, малая доля выручки
  • Упрощённое управление, заказ крупными партиями реже

In [19]:
pd.set_option('display.max_columns', 40)
pd.set_option('display.float_format', '{:.2f}'.format)

In [20]:
df = pd.read_csv('data/data.csv', encoding='1251')

df.head()

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,Катрен г.Химки,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.00,41.08,51.00,12.00,925.00,200000000492.00,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,Катрен г.Химки,ФЛОРА КАВКАЗА ОАО,1.00,18.61,31.00,3.00,9.00,200010010204.00,205,1,1.00
2,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,460864,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,Катрен г.Химки,КОРОЛЕВФАРМ ООО,1.00,132.69,209.00,20.00,9.00,200010010204.00,205,1,2.00
3,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,172823,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,Катрен г.Химки,КОРОЛЕВФАРМ ООО,1.00,133.65,210.00,21.00,9.00,200010010204.00,205,1,3.00
4,2022-08-11,10:33:56,2175,2004598,2,22577,Розничная реализация,18,79056,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,Катрен г.Химки,Новартис Фарма АГ,1.00,709.95,787.00,49.00,925.00,200000000492.00,205,1,1.00

In [21]:
groupped_df = df.groupby('DR_NDrugs').agg({'DR_Kol' : np.sum})

groupped_df

                                                    DR_Kol
DR_NDrugs
7 СЕМЬ ДНЕЙ МАСКА Д/ЛИЦА СУББОТА РОМАНТ. ПЕРЕД ...    1.00
9 МЕСЯЦЕВ ФОЛИЕВАЯ К-ТА 0,4МГ. №30 ТАБ. П/П/О /...    1.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ ОКОПНИК 100МЛ. ТУБА       2.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ САБЕЛЬНИК 100МЛ.          2.00
911-ГЕЛЬ-БАЛЬЗАМ Д/ТЕЛА БИШОФИТ П/БОЛИ В СУСТАВ...    1.00
...                                                    ...
Я САМАЯ ВАТНЫЕ ПАЛОЧКИ №100 СТАКАН                    1.00
ЯНТАРНАЯ К-ТА 100МГ. №10 ТАБ. (БАД) /МАРБИОФАРМ/      2.00
ЯНТАРНАЯ К-ТА ПРЕМИУМ 100МГ. №20 ТАБ. (БАД) /БА...    1.00
ЯНТАРНАЯ К-ТА ФОРП 100МГ. №10 ТАБ.                    3.00
ЯРИНА №21 ТАБ. П/П/О                                  1.00

[1876 rows x 1 columns]

In [22]:
# Вклад продажи товара в общих продажах

groupped_df = (groupped_df['DR_Kol'] / sum(groupped_df['DR_Kol'])).sort_values(ascending=False)

groupped_df

DR_NDrugs
ПАКЕТ                                                                         0.03
ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /ЛЕККО/                          0.01
НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/                              0.01
ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/                                   0.01
СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/                            0.01
                                                                              ...
НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. /МОСФАРМ/                      0.00
СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]                             0.00
СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]                              0.00
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР. Н/ОПУДР Р.L №50 (25ПАР)       0.00
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/ОПУДР. Р.L №100 (50ПАР) [SFM]   0.00
Name: DR_Kol, Length: 1876, dtype: float64

In [24]:
groupped_df = groupped_df.cumsum().reset_index()

groupped_df

                                              DR_NDrugs  DR_Kol
0                                                 ПАКЕТ    0.03
1     ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /...    0.04
2      НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/    0.05
3           ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/    0.06
4     СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТ...    0.07
...                                                 ...     ...
1871  НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ....    1.00
1872  СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]    1.00
1873   СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]    1.00
1874  ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР...    1.00
1875  СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/...    1.00

[1876 rows x 2 columns]

In [28]:
groupped_df['ABC'] = np.where(groupped_df['DR_Kol'] < 0.8, 'A', np.where(groupped_df['DR_Kol'] < 0.95, 'B', 'C'))

groupped_df[groupped_df['ABC'] == 'B']

                                              DR_NDrugs  DR_Kol ABC
938                        ВИАГРА 100МГ. №12 ТАБ. П/П/О    0.80   B
939   ВЕТОРОН ВИТ.Е 2% 20МЛ. Р-Р Д/ПРИЕМА ВНУТРЬ ФЛ....    0.80   B
940                 РОКСЕРА 10МГ. №90 ТАБ. П/П/О /KRKA/    0.80   B
941               РОКС ЗУБ.ЩЕТКА СЕНСИТИВ МЯГКАЯ [ROCS]    0.80   B
942   ПРОТОПИК 0,1% 30Г. МАЗЬ Д/НАРУЖ.ПРИМ. ТУБА /ЛЕ...    0.80   B
...                                                 ...     ...  ..
1621              НИФЕДИПИН 10МГ. №50 ТАБ. П/П/О /ОЗОН/    0.95   B
1622        НИТРОФУНГИН-ТЕВА 1% 25МЛ. №1 СПИРТ. Р-Р ФЛ.    0.95   B
1623    ОРТОФЕН 2% 50Г. МАЗЬ Д/НАРУЖ.ПРИМ. ТУБА /ВЕРТЕ/    0.95   B
1624  НОРМОБАКТ-L 3Г. №10 ПОР. Д/-Р-РА Д/ПРИЕМА ВНУТ...    0.95   B
1625                           НООТРОП 400МГ. №48 КАПС.    0.95   B

[688 rows x 3 columns]

Многомерный ABC анализ

In [30]:
groupped_df = df.groupby('DR_NDrugs').agg({
    'DR_Kol' : np.sum,
    'DR_CRoz' : np.sum
})

groupped_df

                                                    DR_Kol  DR_CRoz
DR_NDrugs
7 СЕМЬ ДНЕЙ МАСКА Д/ЛИЦА СУББОТА РОМАНТ. ПЕРЕД ...    1.00    93.00
9 МЕСЯЦЕВ ФОЛИЕВАЯ К-ТА 0,4МГ. №30 ТАБ. П/П/О /...    1.00   144.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ ОКОПНИК 100МЛ. ТУБА       2.00   216.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ САБЕЛЬНИК 100МЛ.          2.00   208.00
911-ГЕЛЬ-БАЛЬЗАМ Д/ТЕЛА БИШОФИТ П/БОЛИ В СУСТАВ...    1.00   100.00
...                                                    ...      ...
Я САМАЯ ВАТНЫЕ ПАЛОЧКИ №100 СТАКАН                    1.00    65.00
ЯНТАРНАЯ К-ТА 100МГ. №10 ТАБ. (БАД) /МАРБИОФАРМ/      2.00    27.00
ЯНТАРНАЯ К-ТА ПРЕМИУМ 100МГ. №20 ТАБ. (БАД) /БА...    1.00    52.00
ЯНТАРНАЯ К-ТА ФОРП 100МГ. №10 ТАБ.                    3.00    28.00
ЯРИНА №21 ТАБ. П/П/О                                  1.00  1292.00

[1876 rows x 2 columns]

In [31]:
groupped_df['rel_kol'] = (groupped_df['DR_Kol'] / sum(groupped_df['DR_Kol']))
groupped_df

                                                    DR_Kol  DR_CRoz  rel_kol
DR_NDrugs
7 СЕМЬ ДНЕЙ МАСКА Д/ЛИЦА СУББОТА РОМАНТ. ПЕРЕД ...    1.00    93.00     0.00
9 МЕСЯЦЕВ ФОЛИЕВАЯ К-ТА 0,4МГ. №30 ТАБ. П/П/О /...    1.00   144.00     0.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ ОКОПНИК 100МЛ. ТУБА       2.00   216.00     0.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ САБЕЛЬНИК 100МЛ.          2.00   208.00     0.00
911-ГЕЛЬ-БАЛЬЗАМ Д/ТЕЛА БИШОФИТ П/БОЛИ В СУСТАВ...    1.00   100.00     0.00
...                                                    ...      ...      ...
Я САМАЯ ВАТНЫЕ ПАЛОЧКИ №100 СТАКАН                    1.00    65.00     0.00
ЯНТАРНАЯ К-ТА 100МГ. №10 ТАБ. (БАД) /МАРБИОФАРМ/      2.00    27.00     0.00
ЯНТАРНАЯ К-ТА ПРЕМИУМ 100МГ. №20 ТАБ. (БАД) /БА...    1.00    52.00     0.00
ЯНТАРНАЯ К-ТА ФОРП 100МГ. №10 ТАБ.                    3.00    28.00     0.00
ЯРИНА №21 ТАБ. П/П/О                                  1.00  1292.00     0.00

[1876 rows x 3 columns]

In [33]:
groupped_df = groupped_df.sort_values('rel_kol', ascending=False)
groupped_df

                                                    DR_Kol  DR_CRoz  rel_kol
DR_NDrugs
ПАКЕТ                                               126.00   248.00     0.03
ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /Л...   60.00  2280.00     0.01
НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/     48.00   552.00     0.01
ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/          40.00    28.00     0.01
СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/   35.00  4215.00     0.01
...                                                    ...      ...      ...
НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. ...    0.06   669.00     0.00
СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]     0.05   918.00     0.00
СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]      0.04  1324.00     0.00
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР....    0.04  2000.00     0.00
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/О...    0.02   988.00     0.00

[1876 rows x 3 columns]

In [34]:
groupped_df['cumsum_kol'] = groupped_df['rel_kol'].cumsum()

groupped_df

,DR_Kol,DR_CRoz,rel_kol,cumsum_kol
DR_NDrugs,,,,
ПАКЕТ,126.00,248.00,0.03,0.03
"ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /ЛЕККО/",60.00,2280.00,0.01,0.04
"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",48.00,552.00,0.01,0.05
"ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/",40.00,28.00,0.01,0.06
"СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/",35.00,4215.00,0.01,0.07
...,...,...,...,...
"НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. /МОСФАРМ/",0.06,669.00,0.00,1.00
"СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]",0.05,918.00,0.00,1.00
"СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]",0.04,1324.00,0.00,1.00
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР. Н/ОПУДР Р.L №50 (25ПАР),0.04,2000.00,0.00,1.00
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/ОПУДР. Р.L №100 (50ПАР) [SFM],0.02,988.00,0.00,1.00

In [38]:
groupped_df['ABC_kol'] = np.where(groupped_df['cumsum_kol'] < 0.8, 'A', np.where(groupped_df['cumsum_kol'] < 0.95, 'B', 'C'))

groupped_df

,DR_Kol,DR_CRoz,rel_kol,cumsum_kol,ABC,ABC_kol
DR_NDrugs,,,,,,
ПАКЕТ,126.00,248.00,0.03,0.03,A,A
"ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /ЛЕККО/",60.00,2280.00,0.01,0.04,A,A
"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",48.00,552.00,0.01,0.05,A,A
"ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/",40.00,28.00,0.01,0.06,A,A
"СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/",35.00,4215.00,0.01,0.07,A,A
...,...,...,...,...,...,...
"НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. /МОСФАРМ/",0.06,669.00,0.00,1.00,C,C
"СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]",0.05,918.00,0.00,1.00,C,C
"СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]",0.04,1324.00,0.00,1.00,C,C
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР. Н/ОПУДР Р.L №50 (25ПАР),0.04,2000.00,0.00,1.00,C,C
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/ОПУДР. Р.L №100 (50ПАР) [SFM],0.02,988.00,0.00,1.00,C,C