In [31]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [32]:
df = pd.read_csv('itresume-users-pandas.csv', sep=';', skiprows=1, encoding='1251')

params = dict()

params['Имена столбцлов'] = df.columns.tolist()
params['Размер'] = df.size
params['Форма'] = df.shape

print(params)

{'Имена столбцлов': ['id', 'username', 'date_joined'], 'Размер': 300, 'Форма': (100, 3)}

In [33]:
pd.to_datetime(df['date_joined']).dt.day_of_week.unique()

array([6, 3, 2, 5, 1, 4, 0], dtype=int32)

In [34]:
pd.to_datetime(df['date_joined']).dt.day_of_week.unique()

m = {
    0 : 'Понедельник',
    1 : 'Вторник',
    2 : 'Среда',
    3 : 'Четверг',
    4 : 'Пятница',
    5 : 'Суббота',
    6 : 'Воскресенье'
}

df['weekday'] = pd.to_datetime(df['date_joined']).dt.day_of_week

df['weekday'] = df['weekday'].map(m)

df['date'] = pd.to_datetime(df['date_joined']).dt.date

df

      id       username          date_joined      weekday        date
0    416  nsosabisfsobm  2022-01-02 12:22:43  Воскресенье  2022-01-02
1     43    NbabnnbTona  2021-07-01 09:11:42      Четверг  2021-07-01
2     50           jbdn  2021-08-04 09:01:56        Среда  2021-08-04
3    249       Kbaoxsnb  2021-11-27 07:03:35      Суббота  2021-11-27
4     77   bxakbasmo$$$  2021-11-09 14:31:46      Вторник  2021-11-09
..   ...            ...                  ...          ...         ...
95   946     Mbbn$xb$eo  2022-01-29 18:04:23      Суббота  2022-01-29
96   947            NaN  2022-01-29 18:31:26      Суббота  2022-01-29
97  1050     nsosabndsi  2022-02-01 21:02:59      Вторник  2022-02-01
98  1076    SbsdSaobdox  2022-02-02 19:31:21        Среда  2022-02-02
99  1090           Addb  2022-02-03 13:14:15      Четверг  2022-02-03

[100 rows x 5 columns]

In [35]:
res = df.groupby('weekday')[['date']].agg(['count', 'nunique']).reset_index()

res

       weekday  date
               count nunique
0  Воскресенье    11       6
1      Вторник    12       7
2  Понедельник    18       6
3      Пятница     9       6
4        Среда    19      11
5      Суббота    16       8
6      Четверг    15       7

In [36]:
import pandas as pd

df = pd.read_csv('itresume-users-pandas.csv', sep=';', skiprows=1)

fake_usernames = ['fnoxonsnbkbxsnb', 'Jonns21241412', 'fbxbnsn']

df = df[(df['id'] >= 94) & (~df['username'].isin(fake_usernames))]

df['cohort'] = pd.to_datetime(df['date_joined']).dt.strftime('%Y-%m')

res = df.groupby('cohort').size().pipe(lambda x: x / x.sum() * 100).round(2)

res.name = 'proportion'

res

cohort
2021-11    37.36
2021-12    31.87
2022-01    26.37
2022-02     3.30
2022-04     1.10
Name: proportion, dtype: float64

In [37]:
df

      id       username          date_joined   cohort
0    416  nsosabisfsobm  2022-01-02 12:22:43  2022-01
3    249       Kbaoxsnb  2021-11-27 07:03:35  2021-11
7   2633           Eabx  2022-04-06 08:52:40  2022-04
12   219         Sbjssb  2021-11-24 17:11:49  2021-11
13   220      Nsobdbs78  2021-11-24 17:25:31  2021-11
..   ...            ...                  ...      ...
95   946     Mbbn$xb$eo  2022-01-29 18:04:23  2022-01
96   947            NaN  2022-01-29 18:31:26  2022-01
97  1050     nsosabndsi  2022-02-01 21:02:59  2022-02
98  1076    SbsdSaobdox  2022-02-02 19:31:21  2022-02
99  1090           Addb  2022-02-03 13:14:15  2022-02

[91 rows x 4 columns]

In [38]:
import pandas as pd

df = pd.read_csv('itresume-coderun.csv', sep=',')

df

          id               created_at  problem_id  user_id  language_id
0          1  2021-04-07 06:06:20.000          13       10            3
1          2  2021-03-31 07:10:06.000          15       13            3
2          3  2021-04-04 14:55:26.000           1        6            3
3          4  2021-03-29 21:24:51.000          26        4            3
4          5  2021-03-30 11:29:12.000          21       18            3
...      ...                      ...         ...      ...          ...
55717  55718  2022-05-17 09:00:51.743         101      171            2
55718  55719  2022-05-17 09:01:04.210         101      171            2
55719  55720  2022-05-17 09:02:06.203         101      171            2
55720  55721  2022-05-17 09:03:45.265         102      171            2
55721  55722  2022-05-17 09:03:57.645         102      171            2

[55722 rows x 5 columns]

In [39]:
df['cohort'] = pd.to_datetime(df['created_at']).dt.strftime('%Y-%m')

m = {
    3 : 'Python',
    2 : 'SQL'
}

df['language'] = df['language_id'].map(m)

df = df[df['cohort'] >= '2022-01']

user_tasks = df.groupby(['cohort', 'language', 'user_id'])['problem_id'].nunique().reset_index(name='task_count')

df = user_tasks.pivot_table(values='task_count', index=['cohort'], columns=['language'], aggfunc='mean')

df

language    Python        SQL
cohort
2022-01   3.432203   6.763514
2022-02   2.684524   4.742358
2022-03   2.330000   5.277778
2022-04   6.659794   8.073684
2022-05   5.833333  10.451613

In [41]:
import pandas as pd

# Загрузка файла в датафрейм coderun
coderun = pd.read_csv('itresume-coderun.csv')

# Создание переменных для фильтрации
problem_id = [1, 2, 3, 13, 15, 26]
language_id = 2

# Фильтрация с помощью query: оставляем язык 2 и исключаем указанные задачи
df = coderun.query('language_id == @language_id and problem_id not in @problem_id')

df

          id               created_at  problem_id  user_id  language_id
391      392  2021-09-20 18:01:45.592          82       63            2
425      426  2021-09-21 08:10:09.720          75       63            2
426      427  2021-09-21 08:11:21.734          75       63            2
427      428  2021-09-21 08:13:06.417          81       63            2
428      429  2021-09-21 08:13:11.887          81       63            2
...      ...                      ...         ...      ...          ...
55717  55718  2022-05-17 09:00:51.743         101      171            2
55718  55719  2022-05-17 09:01:04.210         101      171            2
55719  55720  2022-05-17 09:02:06.203         101      171            2
55720  55721  2022-05-17 09:03:45.265         102      171            2
55721  55722  2022-05-17 09:03:57.645         102      171            2

[44483 rows x 5 columns]