In [10]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv('itresume-users-pandas.csv', sep=';', skiprows=1, encoding='1251')

params = dict()

params['Имена столбцлов'] = df.columns.tolist()
params['Размер'] = df.size
params['Форма'] = df.shape

print(params)

{'Имена столбцлов': ['id', 'username', 'date_joined'], 'Размер': 300, 'Форма': (100, 3)}

In [12]:
pd.to_datetime(df['date_joined']).dt.day_of_week.unique()

array([6, 3, 2, 5, 1, 4, 0], dtype=int32)

In [13]:
pd.to_datetime(df['date_joined']).dt.day_of_week.unique()

m = {
    0 : 'Понедельник',
    1 : 'Вторник',
    2 : 'Среда',
    3 : 'Четверг',
    4 : 'Пятница',
    5 : 'Суббота',
    6 : 'Воскресенье'
}

df['weekday'] = pd.to_datetime(df['date_joined']).dt.day_of_week

df['weekday'] = df['weekday'].map(m)

df['date'] = pd.to_datetime(df['date_joined']).dt.date

df

      id       username          date_joined      weekday        date
0    416  nsosabisfsobm  2022-01-02 12:22:43  Воскресенье  2022-01-02
1     43    NbabnnbTona  2021-07-01 09:11:42      Четверг  2021-07-01
2     50           jbdn  2021-08-04 09:01:56        Среда  2021-08-04
3    249       Kbaoxsnb  2021-11-27 07:03:35      Суббота  2021-11-27
4     77   bxakbasmo$$$  2021-11-09 14:31:46      Вторник  2021-11-09
..   ...            ...                  ...          ...         ...
95   946     Mbbn$xb$eo  2022-01-29 18:04:23      Суббота  2022-01-29
96   947            NaN  2022-01-29 18:31:26      Суббота  2022-01-29
97  1050     nsosabndsi  2022-02-01 21:02:59      Вторник  2022-02-01
98  1076    SbsdSaobdox  2022-02-02 19:31:21        Среда  2022-02-02
99  1090           Addb  2022-02-03 13:14:15      Четверг  2022-02-03

[100 rows x 5 columns]

In [17]:
res = df.groupby('weekday')[['date']].agg(['count', 'nunique']).reset_index()

res

       weekday  date
               count nunique
0  Воскресенье    11       6
1      Вторник    12       7
2  Понедельник    18       6
3      Пятница     9       6
4        Среда    19      11
5      Суббота    16       8
6      Четверг    15       7

In [24]:
import pandas as pd

df = pd.read_csv('itresume-users-pandas.csv', sep=';', skiprows=1)

fake_usernames = ['fnoxonsnbkbxsnb', 'Jonns21241412', 'fbxbnsn']

df = df[(df['id'] >= 94) & (~df['username'].isin(fake_usernames))]

df['cohort'] = pd.to_datetime(df['date_joined']).dt.strftime('%Y-%m')

res = df.groupby('cohort').size().pipe(lambda x: x / x.sum() * 100).round(2)

res.name = 'proportion'

res

cohort
2021-11    37.36
2021-12    31.87
2022-01    26.37
2022-02     3.30
2022-04     1.10
Name: proportion, dtype: float64

In [23]:
df

      id       username          date_joined   cohort
0    416  nsosabisfsobm  2022-01-02 12:22:43  2022-01
3    249       Kbaoxsnb  2021-11-27 07:03:35  2021-11
7   2633           Eabx  2022-04-06 08:52:40  2022-04
12   219         Sbjssb  2021-11-24 17:11:49  2021-11
13   220      Nsobdbs78  2021-11-24 17:25:31  2021-11
..   ...            ...                  ...      ...
95   946     Mbbn$xb$eo  2022-01-29 18:04:23  2022-01
96   947            NaN  2022-01-29 18:31:26  2022-01
97  1050     nsosabndsi  2022-02-01 21:02:59  2022-02
98  1076    SbsdSaobdox  2022-02-02 19:31:21  2022-02
99  1090           Addb  2022-02-03 13:14:15  2022-02

[91 rows x 4 columns]